[build]
  command = "npm run build"
  publish = ".next"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = true
[build.processing.js]
  bundle = false
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[context.production]
  environment = { NODE_VERSION = "14", AWS_LAMBDA_JS_RUNTIME = "nodejs14.x" }

[[plugins]]
  package = "@netlify/plugin-nextjs"